In [3]:
import pandas as pd
from pathlib import Path

In [5]:
syllable_table = pd.read_csv('/home/neel/Desktop/MOUS_hierarchical-representations/guslatho_MOUS_word_syllable_frequencies.csv',index_col=0)
syllable_table

,Word,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs,Min_Log10_FreqCount,Max_Log10_FreqCount,Mean_Log10_FreqCount,Min_Syll_Zipf
0,ik,1,"(6.241737438532683,)","(7.468668823067624,)",6.241737,6.241737,6.241737,7.468669
1,je,1,"(6.249430979053402,)","(7.476362363588343,)",6.249431,6.249431,6.249431,7.476362
2,het,1,"(6.032457179694622,)","(7.259388564229563,)",6.032457,6.032457,6.032457,7.259389
3,de,1,"(6.234172950952972,)","(7.461104335487914,)",6.234173,6.234173,6.234173,7.461104
4,dat,1,"(6.012697215956926,)","(7.239628600491868,)",6.012697,6.012697,6.012697,7.239629
...,...,...,...,...,...,...,...,...
278056,aagghh,1,"(0.3010299956639812,)","(1.5279613801989225,)",0.301030,0.301030,0.301030,1.527961
278057,aagezien,3,"(1.5185139398778875, 6.125745990776331, 5.0128...","(2.7454453244128287, 7.352677375311273, 6.2397...",1.518514,6.125746,4.219027,2.745445
278058,aaf,1,"(0.3010299956639812,)","(1.5279613801989225,)",0.301030,0.301030,0.301030,1.527961
278059,aada's,0,(),(),NaN,NaN,NaN,NaN
278060,aachener,3,"(1.5185139398778875, 3.8627870982353443, 4.446...","(2.7454453244128287, 5.0897184827702855, 5.673...",1.518514,4.446708,3.276003,2.745445

In [6]:
transcription_example = pd.read_csv('/media/neel/MOUS/MOUS/MOUS/SynologyDrive/source/sub-A2002/func/sub-A2002_transcription.csv')
transcription_example

,TextGrid,Transcription,AlignOnset,AlignOffset,OnsetPhoneme,OffsetPhoneme,Duration
0,596,keek,10.244,0.46,k,k,0.46
1,596,in,10.914,0.99,I,n,0.32
2,596,die,11.434,1.45,d,i,0.26
3,596,de,11.974,2.01,d,@,0.28
4,596,verbaasd,12.464,2.92,v,t,0.70
...,...,...,...,...,...,...,...
1375,322,het,1280.992,1.68,@,t,0.09
1376,322,nieuwe,1281.082,2.15,n,@,0.47
1377,322,en,1281.552,2.38,E,n,0.23
1378,322,eeuwige,1281.782,2.76,e:,@,0.38
1379,322,Jeruzalem,1282.162,3.68,j,m,0.92

In [8]:
source = Path('/media/neel/MOUS/MOUS/MOUS/SynologyDrive/source')

for subject in source.rglob('sub-A*'):
    if subject.is_dir():
        # Read the transcription file
        transcription = pd.read_csv(str(subject / 'func' / f'{subject.name}_transcription.csv'))
        
        # Rename the column for consistency
        transcription.rename(columns={'Transcription': 'Word'}, inplace=True)
        transcription['Word'] = transcription['Word'].apply(lambda x: str(x).lower())
        # Merge transcription with syllable_table on the Word column
        transcription = transcription.merge(
            syllable_table[['Word', 'Min_Log10_FreqCount', 'Min_Syll_Zipf','Max_Log10_FreqCount', 'Mean_Log10_FreqCount']],
            on='Word',
            how='left'
        )
        
        # Rename columns for clarity
        transcription.rename(
            columns={
                'Min_Log10_FreqCount': 'MinLog10FreqCount',
                'Min_Syll_Zipf': 'MinSyllZipf'
            },
            inplace=True
        )
        outpath = Path(subject / 'func' / 'guslatho_syllabified.csv')
        transcription.to_csv(str(outpath))

In [9]:
transcription

,TextGrid,Word,AlignOnset,AlignOffset,OnsetPhoneme,OffsetPhoneme,Duration,MinLog10FreqCount,MinSyllZipf,Max_Log10_FreqCount,Mean_Log10_FreqCount
0,596,keek,10.244,0.46,k,k,0.46,3.555336,4.782268,3.555336,3.555336
1,596,in,10.914,0.99,I,n,0.32,5.704651,6.931582,5.704651,5.704651
2,596,die,11.434,1.45,d,i,0.26,5.527755,6.754686,5.527755,5.527755
3,596,de,11.974,2.01,d,@,0.28,6.234173,7.461104,6.234173,6.234173
4,596,verbaasd,12.464,2.92,v,t,0.70,2.901458,4.128390,5.884177,4.392817
...,...,...,...,...,...,...,...,...,...,...,...
1375,322,het,1280.992,1.68,@,t,0.09,6.032457,7.259389,6.032457,6.032457
1376,322,nieuwe,1281.082,2.15,n,@,0.47,4.476861,5.703792,5.300413,4.888637
1377,322,en,1281.552,2.38,E,n,0.23,5.823575,7.050507,5.823575,5.823575
1378,322,eeuwige,1281.782,2.76,e:,@,0.38,3.740994,4.967925,6.125746,4.824133
1379,322,jeruzalem,1282.162,3.68,j,m,0.92,3.074451,4.301382,6.249431,4.417044