In [3]:
import pandas as pd
import numpy as np

In [4]:
subtlex = pd.read_csv('/home/neel/Desktop/MOUS_hierarchical-representations/guslatho/syllabificator/subtlex_syllabified.csv',index_col=0)
subtlex

,Word,FREQcount,CDcount,FREQlow,CDlow,FREQlemma,SUBTLEXWF,Zipf,SUBTLEXCD,Lg10CD,dominant.pos,dominant.pos.freq,dominant.pos.lemma,dominant.pos.lemma.freq,all.pos,all.pos.freq,all.pos.lemma.freq,Status,Syllabification
0,ik,1744062,8054,778704,3125,1744527,39883.0334,7.597064,99.8017,3.9061,VNW,1743609,ik,1743944,.VNW.SPEC.N.VZ.,.1743609.448.4.1.,.1743944.448.134.1.,keep,ik
1,je,1600888,8060,1315051,6535,1600923,36608.9449,7.559864,99.8761,3.9064,VNW,1600798,je,1600798,.VNW.SPEC.N.BW.LID.,.1600798.72.15.2.1.,.1600798.72.50.2.1.,keep,je
2,het,1068396,8066,780771,5578,1913811,24431.9717,7.384235,99.9504,3.9067,VNW,735390,het,735395,.VNW.LID.SPEC.WW.N.,.735390.332929.53.22.2.,.735395.332929.53.845403.31.,keep,het
3,de,1061177,8070,903872,6512,1063827,24266.8883,7.381291,100.0000,3.9069,LID,1060098,de,1062748,.LID.VNW.SPEC.VZ.,.1060098.806.272.1.,.1062748.806.272.1.,keep,de
4,dat,965424,8063,715570,6107,965431,22077.2184,7.340221,99.9133,3.9066,VNW,532576,dat,532576,.VNW.VG.SPEC.N.WW.,.532576.432794.51.2.1.,.532576.432794.51.9.1.,keep,dat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278056,aagghh,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,N,1,aagghh,1,.N.,.1.,.1.,keep,aagghh
278057,aagezien,1,1,1,1,1,0.0229,1.656532,0.0124,0.3010,WW,1,aazien,1,.WW.,.1.,.1.,keep,aa-ge-zien
278058,aaf,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,SPEC,1,aaf,1,.SPEC.,.1.,.1.,keep,aaf
278059,aada's,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,N,1,aada,1,.N.,.1.,.1.,keep,NaN
278060,aachener,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,SPEC,1,aachener,1,.SPEC.,.1.,.1.,keep,aa-che-ner

In [ ]:
mous = pd.read_csv('mous_words_syllable_bigram_frequencies.csv',index_col=0)
mous = mous.drop(columns=['IPA','Syllables','Min_Freq_Count','Max_Freq_Count','Mean_Freq_Count'])
mous

,Bigrams,Bigram Occurrence Counts,Zipf,FREQcount,Lg10WF
Word,,,,,
toen,"['to', 'oe', 'en']","[2236591.0, 837795.0, 8542439.0]",6.032333,47514.0,4.676822
de,['de'],[2559661.0],7.381291,1061177.0,6.025788
barkeeper,"['ba', 'ar', 'rk', 'ke', 'ee', 'ep', 'pe', 'er']","[584273.0, 1754491.0, 2174749.0, 3143026.0, 94...",3.622674,184.0,2.264818
die,"['di', 'ie']","[1050254.0, 2076673.0]",6.853871,315041.0,5.498367
irritante,"['ir', 'rr', 'ri', 'it', 'ta', 'an', 'nt', 'te']","[2884214.0, 200692.0, 1787712.0, 333345.0, 892...",3.284921,84.0,1.924279
...,...,...,...,...,...
blije,"['bl', 'li', 'ij', 'je']","[152155.0, 3369152.0, 1639122.0, 913788.0]",3.485836,134.0,2.127105
jongeren,"['jo', 'on', 'ng', 'ge', 'er', 're', 'en']","[866375.0, 2451854.0, 2927082.0, 3692145.0, 67...",3.965097,406.0,2.608526
intens,"['in', 'nt', 'te', 'en', 'ns']","[2264626.0, 1477178.0, 3522714.0, 8542439.0, 6...",3.778748,264.0,2.421604
plezier,"['pl', 'le', 'ez', 'zi', 'ie', 'er']","[97171.0, 4397946.0, 100963.0, 123482.0, 20766...",5.093966,5475.0,3.738384
woonplaats,"['wo', 'oo', 'on', 'np', 'pl', 'la', 'aa', 'at...","[933919.0, 3901750.0, 2451854.0, 16967.0, 9717...",3.241993,76.0,1.880814

In [ ]:
inner = pd.merge(subtlex, mous, on='Word', how='inner')
right = pd.merge(subtlex, mous, on='Word', how='right')

In [ ]:
# Keep just the 'Word' column to compare
inner_words = set(inner['Word'])
right_words = set(right['Word'])

# Words in right but not in inner (i.e., unmatched in subtlex or duplicated)
extra_in_right = right_words - inner_words
print(f"Words in right merge but not in inner: {len(extra_in_right)}")
print(extra_in_right)

Words in right merge but not in inner: 30
{'behangrol', 'bijknipt', 'lampionnen', "fotocamera's", 'veluwe', 'matste', 'volleybalteam', 'knuistjes', 'naaktlopers', 'dodewaard', 'utrechtse', 'trimmers', 'ijslollies', 'fransien', 'luuk', 'keukenhof', 'ongekleurd', 'vocalisten', 'heilsoldaat', 'technoloog', 'u', 'toneelbouwers', 'beetgare', 'sportarts', 'waterland', 'ivo', 'pvda', 'judoka', 'kopieerwerk', "dorien's"}

In [ ]:
#these words are missing from SUBTLEX. given that they are not going into word frequency parameters, no reason to incllude them in sublexical analyses either.

In [ ]:
syl_list = []
from main import syllabificate_word
for word in extra_in_right:
    word = word.split("'s")[0]
    syllabification = syllabificate_word(word,alg='n')
    syl_list.append(syllabification)

Starting Syllabificator...

ModuleNotFoundError: No module named 'chaine'

In [ ]:
syllabifications = list(subtlex['Syllabification'])
syllables = [syllable for word in syllabifications if isinstance(word,str) for syllable in word.split('-')]

In [ ]:
Syllable_Frequency = pd.DataFrame(columns=['Syllable','Count'])
Syllable_Frequency['Syllable'] = np.unique(syllables)
Syllable_Frequency['Count'] = 0
Syllable_Frequency

      Syllable  Count
0            a      0
1           aa      0
2         aabt      0
3         aach      0
4         aacs      0
...        ...    ...
26209      zyt      0
26210      zza      0
26211     zzou      0
26212  zzshing      0
26213      zzy      0

[26214 rows x 2 columns]

In [ ]:
Syllable_Frequency['Count'] = Syllable_Frequency['Syllable'].map(subtlex.assign(Syllabification=subtlex['Syllabification'].str.split('-')).explode('Syllabification').groupby('Syllabification')['FREQcount'].sum()).fillna(0)

In [ ]:
Syllable_Frequency

      Syllable   Count
0            a  179744
1           aa      32
2         aabt       2
3         aach       1
4         aacs       3
...        ...     ...
26209      zyt       1
26210      zza       1
26211     zzou       1
26212  zzshing       4
26213      zzy       2

[26214 rows x 2 columns]

In [ ]:
#subtlex_unaltered = pd.read_excel('SUBTLEX-NL with pos and Zipf.xlsx')

subtlex['n_syllables'] = 0
subtlex['n_syllables'] = subtlex['Syllabification'].apply(
    lambda word: len(word.split('-')) if isinstance(word, str) else 0
)

In [ ]:
dot_product = (subtlex['FREQcount'] * subtlex['n_syllables']).sum()
dot_product = dot_product / 1000000 #of syllable-sized tokens in the (filtered) SUBTLEX-NL corpus

In [ ]:
dot_product

59.301901

In [ ]:
Syllable_Frequency['Syllable Zipf'] = np.log10((Syllable_Frequency['Count'] +1)/ dot_product)
minimum = min(Syllable_Frequency['Syllable Zipf'])
Syllable_Frequency

      Syllable   Count  Syllable Zipf
0            a  179744       3.481588
1           aa      32      -0.254555
2         aabt       2      -1.295947
3         aach       1      -1.472039
4         aacs       3      -1.171009
...        ...     ...            ...
26209      zyt       1      -1.472039
26210      zza       1      -1.472039
26211     zzou       1      -1.472039
26212  zzshing       4      -1.074099
26213      zzy       2      -1.295947

[26214 rows x 3 columns]

In [ ]:
# Syllable_Frequency['Syllable Zipf'] = Syllable_Frequency['Syllable Zipf'] + abs(minimum) + 3
minimum

-1.4720386198010775

In [ ]:
Syllable_Frequency['Syllable Zipf'] = Syllable_Frequency['Syllable Zipf'] + 3 #Following the zipf transformation for words...

In [ ]:
Syllable_Frequency

      Syllable   Count  Syllable Zipf
0            a  179744       6.481588
1           aa      32       2.745445
2         aabt       2       1.704053
3         aach       1       1.527961
4         aacs       3       1.828991
...        ...     ...            ...
26209      zyt       1       1.527961
26210      zza       1       1.527961
26211     zzou       1       1.527961
26212  zzshing       4       1.925901
26213      zzy       2       1.704053

[26214 rows x 3 columns]

In [ ]:
Syllable_Frequency['Log10_Count'] = np.log10(Syllable_Frequency['Count']+1)
Syllable_Frequency

      Syllable   Count  Syllable Zipf  Log10_Count
0            a  179744       6.481588     5.254657
1           aa      32       2.745445     1.518514
2         aabt       2       1.704053     0.477121
3         aach       1       1.527961     0.301030
4         aacs       3       1.828991     0.602060
...        ...     ...            ...          ...
26209      zyt       1       1.527961     0.301030
26210      zza       1       1.527961     0.301030
26211     zzou       1       1.527961     0.301030
26212  zzshing       4       1.925901     0.698970
26213      zzy       2       1.704053     0.477121

[26214 rows x 4 columns]

In [ ]:
#concatenate back to SUBTLEX
subtlex['Log10_Syllable_FREQcounts'] = [() for _ in range(len(subtlex))]
subtlex['Syllable_Zipfs'] = [() for _ in range(len(subtlex))]
subtlex

,Word,FREQcount,CDcount,FREQlow,CDlow,FREQlemma,SUBTLEXWF,Zipf,SUBTLEXCD,Lg10CD,...,dominant.pos.lemma,dominant.pos.lemma.freq,all.pos,all.pos.freq,all.pos.lemma.freq,Status,Syllabification,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs
0,ik,1744062,8054,778704,3125,1744527,39883.0334,7.597064,99.8017,3.9061,...,ik,1743944,.VNW.SPEC.N.VZ.,.1743609.448.4.1.,.1743944.448.134.1.,keep,ik,1,(),()
1,je,1600888,8060,1315051,6535,1600923,36608.9449,7.559864,99.8761,3.9064,...,je,1600798,.VNW.SPEC.N.BW.LID.,.1600798.72.15.2.1.,.1600798.72.50.2.1.,keep,je,1,(),()
2,het,1068396,8066,780771,5578,1913811,24431.9717,7.384235,99.9504,3.9067,...,het,735395,.VNW.LID.SPEC.WW.N.,.735390.332929.53.22.2.,.735395.332929.53.845403.31.,keep,het,1,(),()
3,de,1061177,8070,903872,6512,1063827,24266.8883,7.381291,100.0000,3.9069,...,de,1062748,.LID.VNW.SPEC.VZ.,.1060098.806.272.1.,.1062748.806.272.1.,keep,de,1,(),()
4,dat,965424,8063,715570,6107,965431,22077.2184,7.340221,99.9133,3.9066,...,dat,532576,.VNW.VG.SPEC.N.WW.,.532576.432794.51.2.1.,.532576.432794.51.9.1.,keep,dat,1,(),()
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278056,aagghh,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aagghh,1,.N.,.1.,.1.,keep,aagghh,1,(),()
278057,aagezien,1,1,1,1,1,0.0229,1.656532,0.0124,0.3010,...,aazien,1,.WW.,.1.,.1.,keep,aa-ge-zien,3,(),()
278058,aaf,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aaf,1,.SPEC.,.1.,.1.,keep,aaf,1,(),()
278059,aada's,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aada,1,.N.,.1.,.1.,keep,NaN,0,(),()
278060,aachener,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aachener,1,.SPEC.,.1.,.1.,keep,aa-che-ner,3,(),()

In [ ]:
# Create a mapping from syllable to its frequency and zipf value for fast lookups
syllable_map_log_count = Syllable_Frequency.set_index('Syllable')['Log10_Count']
syllable_map_zipf = Syllable_Frequency.set_index('Syllable')['Syllable Zipf']

# Define a function to apply to each row
def get_syllable_stats(syllabification):
    if not isinstance(syllabification, str):
        return (), ()
    syllables = syllabification.split('-')
    log_counts = tuple(syllable_map_log_count.get(s) for s in syllables)
    zipfs = tuple(syllable_map_zipf.get(s) for s in syllables)
    return log_counts, zipfs

# Apply the function to the 'Syllabification' column
stats = subtlex['Syllabification'].apply(get_syllable_stats)

# Assign the results back to the DataFrame
subtlex['Log10_Syllable_FREQcounts'], subtlex['Syllable_Zipfs'] = zip(*stats)

In [ ]:
subtlex

,Word,FREQcount,CDcount,FREQlow,CDlow,FREQlemma,SUBTLEXWF,Zipf,SUBTLEXCD,Lg10CD,...,dominant.pos.lemma,dominant.pos.lemma.freq,all.pos,all.pos.freq,all.pos.lemma.freq,Status,Syllabification,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs
0,ik,1744062,8054,778704,3125,1744527,39883.0334,7.597064,99.8017,3.9061,...,ik,1743944,.VNW.SPEC.N.VZ.,.1743609.448.4.1.,.1743944.448.134.1.,keep,ik,1,"(6.241737438532683,)","(7.468668823067624,)"
1,je,1600888,8060,1315051,6535,1600923,36608.9449,7.559864,99.8761,3.9064,...,je,1600798,.VNW.SPEC.N.BW.LID.,.1600798.72.15.2.1.,.1600798.72.50.2.1.,keep,je,1,"(6.249430979053402,)","(7.476362363588343,)"
2,het,1068396,8066,780771,5578,1913811,24431.9717,7.384235,99.9504,3.9067,...,het,735395,.VNW.LID.SPEC.WW.N.,.735390.332929.53.22.2.,.735395.332929.53.845403.31.,keep,het,1,"(6.032457179694622,)","(7.259388564229563,)"
3,de,1061177,8070,903872,6512,1063827,24266.8883,7.381291,100.0000,3.9069,...,de,1062748,.LID.VNW.SPEC.VZ.,.1060098.806.272.1.,.1062748.806.272.1.,keep,de,1,"(6.234172950952972,)","(7.461104335487914,)"
4,dat,965424,8063,715570,6107,965431,22077.2184,7.340221,99.9133,3.9066,...,dat,532576,.VNW.VG.SPEC.N.WW.,.532576.432794.51.2.1.,.532576.432794.51.9.1.,keep,dat,1,"(6.012697215956926,)","(7.239628600491868,)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278056,aagghh,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aagghh,1,.N.,.1.,.1.,keep,aagghh,1,"(0.3010299956639812,)","(1.5279613801989225,)"
278057,aagezien,1,1,1,1,1,0.0229,1.656532,0.0124,0.3010,...,aazien,1,.WW.,.1.,.1.,keep,aa-ge-zien,3,"(1.5185139398778875, 6.125745990776331, 5.0128...","(2.7454453244128287, 7.352677375311273, 6.2397..."
278058,aaf,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aaf,1,.SPEC.,.1.,.1.,keep,aaf,1,"(0.3010299956639812,)","(1.5279613801989225,)"
278059,aada's,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aada,1,.N.,.1.,.1.,keep,NaN,0,(),()
278060,aachener,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aachener,1,.SPEC.,.1.,.1.,keep,aa-che-ner,3,"(1.5185139398778875, 3.8627870982353443, 4.446...","(2.7454453244128287, 5.0897184827702855, 5.673..."

In [ ]:
subtlex_essential = subtlex[['Word','n_syllables','Log10_Syllable_FREQcounts','Syllable_Zipfs']]
subtlex_essential = subtlex_essential.drop_duplicates()

In [ ]:
# Handle empty tuples in 'Log10_Syllable_FREQcounts'
subtlex_essential['Min_Log10_FreqCount'] = subtlex_essential['Log10_Syllable_FREQcounts'].apply(
    lambda x: min(x) if x else None
)

subtlex_essential['Max_Log10_FreqCount'] = subtlex_essential['Log10_Syllable_FREQcounts'].apply(
    lambda x: max(x) if x else None
)
subtlex_essential['Mean_Log10_FreqCount'] = subtlex_essential['Log10_Syllable_FREQcounts'].apply(
    lambda x: np.mean(x) if x else None
)

# Handle empty tuples in 'Syllable_Zipfs'
subtlex_essential['Min_Syll_Zipf'] = subtlex_essential['Syllable_Zipfs'].apply(
    lambda x: min(x) if x else None
)

subtlex_essential

,Word,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs,Min_Log10_FreqCount,Min_Syll_Zipf
0,ik,1,"(6.241737438532683,)","(7.468668823067624,)",6.241737,7.468669
1,je,1,"(6.249430979053402,)","(7.476362363588343,)",6.249431,7.476362
2,het,1,"(6.032457179694622,)","(7.259388564229563,)",6.032457,7.259389
3,de,1,"(6.234172950952972,)","(7.461104335487914,)",6.234173,7.461104
4,dat,1,"(6.012697215956926,)","(7.239628600491868,)",6.012697,7.239629
...,...,...,...,...,...,...
278056,aagghh,1,"(0.3010299956639812,)","(1.5279613801989225,)",0.301030,1.527961
278057,aagezien,3,"(1.5185139398778875, 6.125745990776331, 5.0128...","(2.7454453244128287, 7.352677375311273, 6.2397...",1.518514,2.745445
278058,aaf,1,"(0.3010299956639812,)","(1.5279613801989225,)",0.301030,1.527961
278059,aada's,0,(),(),NaN,NaN
278060,aachener,3,"(1.5185139398778875, 3.8627870982353443, 4.446...","(2.7454453244128287, 5.0897184827702855, 5.673...",1.518514,2.745445

In [ ]:
# Filter rows where any column contains None
rows_with_none = subtlex[subtlex.isnull().any(axis=1)]

# Display the rows
rows_with_none

,Word,FREQcount,CDcount,FREQlow,CDlow,FREQlemma,SUBTLEXWF,Zipf,SUBTLEXCD,Lg10CD,...,dominant.pos.lemma,dominant.pos.lemma.freq,all.pos,all.pos.freq,all.pos.lemma.freq,Status,Syllabification,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs
107,oké,52889,5371,15315,1554,52890,1209.4603,6.078876,66.5551,3.7301,...,oké,37100,.N.ADJ.TSW.SPEC.WW.,.37099.15304.304.174.8.,.37100.15304.304.174.8.,keep,NaN,0,(),()
162,hé,32232,5238,12489,1914,32232,737.0781,5.863803,64.9071,3.7192,...,hé,32172,.BW.SPEC.VZ.ADJ.VG.,.32172.50.7.2.1.,.32172.50.7.2.1.,keep,NaN,0,(),()
186,één,27493,5297,27249,5253,27637,628.7071,5.794740,65.6382,3.7241,...,één,26506,.TW.VNW.SPEC.N.LID.,.26365.849.232.24.23.,.26506.849.233.26.23.,keep,NaN,0,(),()
322,hè,14102,3357,13517,3252,14102,322.4831,5.504814,41.5985,3.5261,...,hè,13657,.N.BW.,.13657.445.,.13657.445.,keep,NaN,0,(),()
567,eén,6562,3215,45,13,6563,150.0592,5.172605,39.8389,3.5073,...,eén,3402,.TW.SPEC.N.WW.ADJ.,.3402.3117.37.5.1.,.3402.3117.38.5.1.,keep,NaN,0,(),()
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277580,aanvalscommando's,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aanvalscommando,1,.N.,.1.,.1.,keep,NaN,0,(),()
277684,aanraakbarrière,1,1,1,1,1,0.0229,1.656532,0.0124,0.3010,...,aanraakbarrière,1,.N.,.1.,.1.,keep,NaN,0,(),()
277756,aanlegcoördinaten,1,1,1,1,1,0.0229,1.656532,0.0124,0.3010,...,aanlegcoördinaten,1,.WW.,.1.,.1.,keep,NaN,0,(),()
278035,aan's,1,1,1,1,1,0.0229,1.656532,0.0124,0.3010,...,aan's,1,.N.,.1.,.1.,keep,NaN,0,(),()
278059,aada's,1,1,0,0,1,0.0229,1.656532,0.0124,0.3010,...,aada,1,.N.,.1.,.1.,keep,NaN,0,(),()

In [ ]:
subtlex_essential.to_csv('guslatho_MOUS_word_syllable_frequencies.csv')
subtlex_essential

,Word,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs,Min_Log10_FreqCount,Min_Syll_Zipf
0,ik,1,"(6.241737438532683,)","(7.468668823067624,)",6.241737,7.468669
1,je,1,"(6.249430979053402,)","(7.476362363588343,)",6.249431,7.476362
2,het,1,"(6.032457179694622,)","(7.259388564229563,)",6.032457,7.259389
3,de,1,"(6.234172950952972,)","(7.461104335487914,)",6.234173,7.461104
4,dat,1,"(6.012697215956926,)","(7.239628600491868,)",6.012697,7.239629
...,...,...,...,...,...,...
278056,aagghh,1,"(0.3010299956639812,)","(1.5279613801989225,)",0.301030,1.527961
278057,aagezien,3,"(1.5185139398778875, 6.125745990776331, 5.0128...","(2.7454453244128287, 7.352677375311273, 6.2397...",1.518514,2.745445
278058,aaf,1,"(0.3010299956639812,)","(1.5279613801989225,)",0.301030,1.527961
278059,aada's,0,(),(),NaN,NaN
278060,aachener,3,"(1.5185139398778875, 3.8627870982353443, 4.446...","(2.7454453244128287, 5.0897184827702855, 5.673...",1.518514,2.745445

In [ ]:
right

,Word,n_syllables,Log10_Syllable_FREQcounts,Syllable_Zipfs,Bigrams,Bigram Occurrence Counts,Zipf,FREQcount,Lg10WF
0,toen,1.0,"(4.680453364401369,)","(5.90738474893631,)","['to', 'oe', 'en']","[2236591.0, 837795.0, 8542439.0]",6.032333,47514.0,4.676822
1,de,1.0,"(6.234172950952972,)","(7.461104335487914,)",['de'],[2559661.0],7.381291,1061177.0,6.025788
2,barkeeper,3.0,"(3.9745116927373285, 3.177824971864682, 4.7107...","(5.20144307727227, 4.4047563563996235, 5.93769...","['ba', 'ar', 'rk', 'ke', 'ee', 'ep', 'pe', 'er']","[584273.0, 1754491.0, 2174749.0, 3143026.0, 94...",3.622674,184.0,2.264818
3,die,1.0,"(5.527754887527666,)","(6.754686272062608,)","['di', 'ie']","[1050254.0, 2076673.0]",6.853871,315041.0,5.498367
4,irritante,4.0,"(3.0461047872460387, 4.870825118775824, 4.0058...","(4.27303617178098, 6.097756503310765, 5.232755...","['ir', 'rr', 'ri', 'it', 'ta', 'an', 'nt', 'te']","[2884214.0, 200692.0, 1787712.0, 333345.0, 892...",3.284921,84.0,1.924279
...,...,...,...,...,...,...,...,...,...
1937,blije,2.0,"(4.573869100848107, 5.300412859229037)","(5.800800485383048, 6.527344243763977)","['bl', 'li', 'ij', 'je']","[152155.0, 3369152.0, 1639122.0, 913788.0]",3.485836,134.0,2.127105
1938,jongeren,3.0,"(4.668600215163262, 6.125745990776331, 5.48281...","(5.895531599698203, 7.352677375311273, 6.70975...","['jo', 'on', 'ng', 'ge', 'er', 're', 'en']","[866375.0, 2451854.0, 2927082.0, 3692145.0, 67...",3.965097,406.0,2.608526
1939,intens,2.0,"(5.704650611569667, 2.92272545799326)","(6.931581996104608, 4.149656842528201)","['in', 'nt', 'te', 'en', 'ns']","[2264626.0, 1477178.0, 3522714.0, 8542439.0, 6...",3.778748,264.0,2.421604
1940,plezier,2.0,"(3.953807997665307, 3.788521887222473)","(5.180739382200248, 5.015453271757414)","['pl', 'le', 'ez', 'zi', 'ie', 'er']","[97171.0, 4397946.0, 100963.0, 123482.0, 20766...",5.093966,5475.0,3.738384
1941,woonplaats,2.0,"(4.72007657276814, 4.131233594589685)","(5.947007957303082, 5.358164979124627)","['wo', 'oo', 'on', 'np', 'pl', 'la', 'aa', 'at...","[933919.0, 3901750.0, 2451854.0, 16967.0, 9717...",3.241993,76.0,1.880814

In [ ]:
dupes = subtlex_essential[subtlex_essential.duplicated('Word', keep=False)]
print(f"Number of duplicated 'Word' entries: {dupes.shape[0]}")
print(dupes['Word'].value_counts())

Number of duplicated 'Word' entries: 0
Series([], Name: count, dtype: int64)

In [ ]:
extra_in_right

{'beetgare',
 'behangrol',
 'bijknipt',
 'dodewaard',
 "dorien's",
 "fotocamera's",
 'fransien',
 'heilsoldaat',
 'ijslollies',
 'ivo',
 'judoka',
 'keukenhof',
 'knuistjes',
 'kopieerwerk',
 'lampionnen',
 'luuk',
 'matste',
 'naaktlopers',
 'ongekleurd',
 'pvda',
 'sportarts',
 'technoloog',
 'toneelbouwers',
 'trimmers',
 'u',
 'utrechtse',
 'veluwe',
 'vocalisten',
 'volleybalteam',
 'waterland'}

In [ ]:
syl_list = []
from main import syllabificate_word
for word in extra_in_right:
    word = word.split("'s")[0]
    syllabification = syllabificate_word(word,alg='n')
    syl_list.append(syllabification)

In [ ]:
missing_df = pd.DataFrame()
missing_df["Words"] = [word.split("'s")[0] for word in extra_in_right]
missing_df['Syllabifications'] = syl_list

In [ ]:
missing_df = missing_df.rename(columns={'Syllabifications': 'Syllabification', 'Words': 'Word'})
missing_df['n_syllables'] = missing_df['Syllabification'].apply(lambda x: len(x.split('-')))
missing_df

             Word   Syllabification  n_syllables
0          matste           mat-ste            2
1       knuistjes        knuist-jes            2
2       utrechtse       ut-recht-se            3
3       dodewaard       do-de-waard            3
4          veluwe          ve-lu-we            3
5          judoka          ju-do-ka            3
6   toneelbouwers  to-neel-bou-wers            4
7       keukenhof       keu-ken-hof            3
8             ivo              i-vo            2
9        trimmers         trim-mers            2
10           luuk              luuk            1
11       fransien        fran-si-en            3
12      sportarts        sport-arts            2
13     lampionnen     lam-pi-on-nen            4
14     technoloog      tech-no-loog            3
15     vocalisten     vo-ca-lis-ten            4
16              u                 u            1
17     fotocamera    fo-to-ca-me-ra            5
18      waterland       wa-ter-land            3
19     ijslollies      ijs-lol-lies            3
20       beetgare        beet-ga-re            3
21     ongekleurd      on-ge-kleurd            3
22    naaktlopers     naakt-lo-pers            3
23      behangrol       be-hang-rol            3
24           pvda             pv-da            2
25    heilsoldaat     heil-sol-daat            3
26  volleybalteam  vol-ley-bal-team            4
27         dorien          do-ri-en            3
28       bijknipt         bij-knipt            2
29    kopieerwerk    ko-pi-eer-werk            4

In [ ]:
#consider imputing syllable frequencies of words whose zipf frequencies were missing, if the SPM12 analyses don't have enough power.